name: Release

on:
  release:
    types:
      - published

jobs:
  dist:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: |
        cd $GITHUB_WORKSPACE
        yarn install
    - name: Build
      run: yarn build

    - name: Upload
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        asset_path: dist/midi-player.js
        asset_name: midi-player.js
        asset_content_type: application/javascript

    - name: Upload minified
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        asset_path: dist/midi-player.min.js
        asset_name: midi-player.min.js
        asset_content_type: application/javascript
